### ISSUE TITLE
Does not capture stdout on FreeBSD 9.2 amd64 running in Dancer

### ISSUE THREAD

**Issue by amishHammer** [dagolden/Capture-Tiny#15]
p5-Capture-Tiny-0.23
perl5-5.16.3_4
p5-Dancer-1.3119_1

This happens when running under dancer only not when running form a simple script.

**Comment by bentglasstube** [comment]
Here is a minimal example of this not working:

    #!/usr/bin/env perl

    use Capture::Tiny 'capture_stdout';
    use Dancer;

    get '/' => sub {
      my $capture = capture_stdout { system 'echo', 'world'; };
      return "Hello, $capture";
    };

    dance;

**Comment by bentglasstube** [comment]
For what it's worth, this is no longer an issue in Dancer2.

**Comment by xdg** [comment]
If it's fixed in Dancer2, I'm going to close this ticket.  Thanks for verifying the two cases.
