### ISSUE TITLE
JSON::PP dependency

### ISSUE THREAD

**Issue by miyagawa** [dagolden/Capture-Tiny#38]
Why is JSON::PP listed as a runtime dependency to this module? I cannot see any reference in the code for it.

**Comment by xdg** [comment]
Weird.  I'm looking to see if it came in via some dzil plugin.  :-(

**Comment by xdg** [comment]
I think it's this: https://rt.cpan.org/Ticket/Display.html?id=112147

**Comment by xdg** [comment]
0.34 shipped to CPAN as a stopgap measure
