### ISSUE TITLE
tests fail sporadically on a ubuntu vm with perl 5.18.2

### ISSUE THREAD

**Issue by gideondsouza** [dagolden/Capture-Tiny#43]
I'm really having an issue here trying to setup an old Dancer (not Dancer2) app. It fails to install deps when I use cpanm to install Dancer. The first thing to fail seems to be `Capture::Tiny`. Any help would be appreciated, feel like I'm doing something more basic wrong here. I've not in the perl scene for a while now 😢  

[build.txt](https://github.com/dagolden/Capture-Tiny/files/243743/build.txt)

**Comment by xdg** [comment]
Pretty clearly, the warnings that perl is generating are interfering with the expected test output:

```
#   Failed test 'capture|sys|empty|unicode - got STDERR'
#   at t/lib/Cases.pm line 22.
#          got: 'perl: warning: Setting locale failed.
# perl: warning: Please check that your locale settings:
# 	LANGUAGE = (unset),
# 	LC_ALL = (unset),
# 	LC_CTYPE = "UTF-8",
# 	LANG = "en_US.UTF-8"
#     are supported and installed on your system.
# perl: warning: Falling back to the standard locale ("C").
# '
#     expected: ''
```

I'll investigate if it's possible to suppress that warning, but you can fix it by fixing your environment so that perl stops complaining.

**Comment by gideondsouza** [comment]
hey @xdg is this fixed and uploaded to cpan? When I do a `cpanm install Capture::Tiny` it still fails with test failures.

Here is a log again:

[build2.txt](https://github.com/dagolden/Capture-Tiny/files/247002/build2.txt)

**Comment by xdg** [comment]
The stable isn't released yet but you can use the --dev flag for cpanm.

**Comment by gideondsouza** [comment]
Ah yep. Folks at IRC noticed this :) I fixed the environment and everything works. Really appreciate the love ❤️  of you perl devs that I've forgotten, besides forgetting some perl too :/
