### ISSUE TITLE
tee_merged leaves cruft in /tmp

### ISSUE THREAD

**Issue by tomwitt2** [dagolden/Capture-Tiny#45]
Using tee_merged leaves temporary files behind in /tmp on completion.

**Comment by xdg** [comment]
I've tried to replicate this and haven't been able to.  I've set `TMPDIR` to an empty directory and run a script that does `tee_merged`.  I see files in the local tmpdir during the run, but they are cleaned up at the end.

Can you elaborate more on what happened for you?  Or could you please try to provide a reproduction?

Thanks.

**Comment by ggl** [comment]
It's a daemon that's executed by root, double forks in the background, and runs other scripts under lower privileges. Basically it does something in the lines of:

```
use Mojo::IOLoop;
use Proc::Fork;
use Capture::Tiny;

## set up event loop
Mojo::IOLoop->recurring(10 => sub {
	## read config, init logging, do some stuff
	Proc::Fork::parent { exit };
	POSIX::setsid() or die "Could not start a new session: $!\n";
	$SIG{'CHLD'} = 'IGNORE'; # Don't worry about reaping zombies
	## so some other stuff
	Proc::Fork::child {
	eval {
		my ($out, $exit) = Capture::Tiny::capture_merged {
			## drop privileges to the uid/gid specified in the conf file
			if ($< == 0 and defined $user and defined $group) {
				my $uid = getpwnam($user) // die "No such user: $user";
				my $gid = getgrnam($group) // die "No such group: $group";
				## getgrouplist() needed on Linux only; on *BSD this returns undef
				my @gids = getgrouplist($group);
				my $gids;
				if (@gids) {
					$gids = join(' ', @gids);
					$) = $gids if defined $gids; # do setgid _before_ setuid
				}
				else {
					$) = $gid if defined $gid; # do setgid _before_ setuid
				}
				$> = $uid if defined $uid;
				# $log->debug("$0: current privileges: UID $<, EUID $>, GID $(, EGID $)\n");
			}
			system(@command)
		};
	};
	## check $@ and report errors
});
```

**Comment by xdg** [comment]
Can you try it dropping privileges *before* you run `capture_merged`?  Otherwise, I can easily imagine that the new UID doesn't have rights to clean up the old tempfiles.

If that's the case, I'll add that as a caveat to the documentation.

**Comment by ggl** [comment]
Hmm yup I should probably do that in the eval. All the temp file as created with root privileges, so that must be the obvious cause for leaving cruft behind.
